/** Notes adapters: authorization and mutations use the canonical service. */
import express from 'express';
import * as db from '../db.js';
import {createLogger} from '../logger.js';
import {readNoteBoard,readNote,readNoteMembers,updateNote,mutateNote,setNoteLayout,setNoteLayouts} from '../services/note-board.js';
import {noteChangesStream} from '../services/note-changes.js';
import {readGroupedNoteBoard,applyNoteGroupCommand} from '../services/note-groups.js';
const router=express.Router(),log=createLogger('Notes');
const handler=work=>(req,res)=>{try{res.set('Cache-Control','private, no-store');work(req,res);}catch(error){if(!error.status)log.error('',error);res.status(error.status||500).json({error:error.status?error.message:'Internal error',code:error.status||500,...(error.reason?{reason:error.reason}:{})});}};
router.get('/changes',noteChangesStream);
router.get('/members',handler((req,res)=>res.json({data:readNoteMembers(db.get(),req)})));
router.get('/board',handler((req,res)=>res.json({data:readGroupedNoteBoard(db.get(),req)})));
router.post('/group-operations',handler((req,res)=>res.json({data:applyNoteGroupCommand(db.get(),req,req.body)})));
router.get('/',handler((req,res)=>res.json({data:readNoteBoard(db.get(),req).notes})));
router.patch('/layout',handler((req,res)=>res.json({data:setNoteLayouts(db.get(),req,req.body)})));
router.post('/',handler((req,res)=>res.status(201).json({data:updateNote(db.get(),req,null,req.body)})));
router.get('/:id',handler((req,res)=>res.json({data:readNote(db.get(),req,req.params.id)})));
router.put('/:id',handler((req,res)=>res.json({data:updateNote(db.get(),req,req.params.id,req.body)})));
router.patch('/:id/layout',handler((req,res)=>res.json({data:setNoteLayout(db.get(),req,req.params.id,req.body)})));
router.patch('/:id/pin',handler((req,res)=>res.json({data:mutateNote(db.get(),req,req.params.id,'pin',req.body)})));
router.patch('/:id/check',handler((req,res)=>res.json({data:mutateNote(db.get(),req,req.params.id,'check',req.body)})));
router.delete('/:id',handler((req,res)=>{mutateNote(db.get(),req,req.params.id,'delete',{expected_revision:req.query.expected_revision===undefined?undefined:Number(req.query.expected_revision)});res.status(204).end();}));
export default router;
